### ISSUE TITLE
Accessibility: social icons

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#158]
Social media icons at the bottom of the page are flagged as not having alt text for accessibility.
Facebook
Twitter
Instagram

"Follow the BMRC on Facebook"
"........................... on Twitter"
"............................ on Instagram"
should suffice!

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/57d7520d4d64b4985c3949883d7b5dce88c12561 and live on both bmrc-test.lib and bmrc.lib. I'm going to close this issue out, please feel free to re-open it if necessary.

**Comment by MomoMoses** [comment]
awesome!

**Comment by MomoMoses** [comment]
the pages were re-crawled an hour ago, but they still show the error. Here is what they suggest as a fix for the code:
`<a href="http://www.w3.org/WAI"> <img src="..." alt="Web Accessibility Initiative"/></a>
`
The order of things is a little different than ours, is all I can see. Can't imagine why that would matter, can you?
Here's what we have: `<a alt="Follow the BMRC on Facebook" href="https://www.facebook.com/1BMRC">
` plus an svg element with the image specs and source... thoughts? Wait, I think I may see the logical inconsistency -- it's an alt text for the IMAGE, not for the LINK. They _say_ "link" but they really mean "an image used as a link," I think.

What if we put the alt text in the tag used for the icon, i.e. `<i>`? Seems like SiteImprove is not up with the latest greatest cool web dev!

This issue, since it occurs on almost every page, really drags down the score... :(

**Comment by johnjung** [comment]
Ok- this shows up in Siteimprove as "Link without a text alternative." I switched the alt attribute on the `<a>` elements to an aria-label- as far as I can tell that fixes the issue. Please take a look at the site and at Siteimprove to confirm that this is fixed.

**Comment by MomoMoses** [comment]
I think so! Doesn't show up. :)
